#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#   ExpManager ConfigFile!
#   Author SiriuseR(dejiplus)
#   License GPLv3
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>#
#   Debug Config   #
#<<<<<<<<<<<<<<<<<<#
Debug: false

#>>>>>>>>>>>>>>>>>>#
#   DO NOT TOUCH   #
#<<<<<<<<<<<<<<<<<<#
ConfigVersion: 2