#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#   ExpManager ConfigFile!
#   Author SiriuseR(dejiplus)
#   License GPLv3
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#>>>>>>>>>>>>>>>>>>>>>>#
#   EntityExP Config   #
#<<<<<<<<<<<<<<<<<<<<<<#
Entity:

#>>>>>>>>>>>>>>>>>>>>>>#
#   BlockExp Config    #
#<<<<<<<<<<<<<<<<<<<<<<#
Block:

#>>>>>>>>>>>>>>>>>>>>>>#
#   Debug Config       #
#<<<<<<<<<<<<<<<<<<<<<<#
Debug: false

#>>>>>>>>>>>>>>>>>>>>>>#
#   DO NOT TOUCH       #
#<<<<<<<<<<<<<<<<<<<<<<#
ConfigVersion: 2