name: SR-ExpManager
version: version-number-unknown
description: ExpManagementPlugin.
authors: [SiriuseR]
website: http://www.siriuser.net/
main: net.siriuser.expmanager.ExpManager
commands:
permissions: