name: SR-ExpManager
version: version-number-unknown
description: SR-ExpManager
authors: [SiriuseR]
softdepend: [SR-CoreLib]
website: http://www.siriuser.net/
main: net.siriuser.SRExpManager.SRExpManager
commands:
permissions: